In [2]:
#Word Embedding Techniques using Embedding Layer in Keras
### Libraries USed Tensorflow> 2.0  and keras
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
#we need to convert these sentences in one hot
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent




['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
#meaning what is the size of the dictionary
voc_size=10000



In [6]:
#One Hot Representation
onehot_repr=[one_hot(words,voc_size)for words in sent] 
#i am going to pass this word to one hot function where i have to pass word and other is vocsize
#with this we will be getting index from the dictionary
print(onehot_repr)

#the index for 'the' is 7117 out of the 10000 voc size
#index for glass is 318 and so on
#when u see the first and second sentence ,they are almost same, and their indexes also matches


[[7117, 318, 9, 3154], [7117, 318, 9, 4814], [7117, 4331, 9, 2247], [4326, 7338, 2809, 2826, 2162], [4326, 7338, 2809, 2826, 3672], [8459, 7117, 7221, 9, 487], [4594, 1270, 5893, 2826]]


In [7]:
#Word Embedding Represntation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences#
from tensorflow.keras.models import Sequential




In [8]:
import numpy as np



In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)



[[   0    0    0    0 7117  318    9 3154]
 [   0    0    0    0 7117  318    9 4814]
 [   0    0    0    0 7117 4331    9 2247]
 [   0    0    0 4326 7338 2809 2826 2162]
 [   0    0    0 4326 7338 2809 2826 3672]
 [   0    0    0 8459 7117 7221    9  487]
 [   0    0    0    0 4594 1270 5893 2826]]


In [10]:

dim=10

#dimension mean features



In [11]:

model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')




In [12]:
model.summary()




Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))



[[[ 0.01076838  0.04307185 -0.01128992 -0.01341581 -0.03547974
    0.00670798  0.03213383 -0.02241655 -0.00337216 -0.00476903]
  [ 0.01076838  0.04307185 -0.01128992 -0.01341581 -0.03547974
    0.00670798  0.03213383 -0.02241655 -0.00337216 -0.00476903]
  [ 0.01076838  0.04307185 -0.01128992 -0.01341581 -0.03547974
    0.00670798  0.03213383 -0.02241655 -0.00337216 -0.00476903]
  [ 0.01076838  0.04307185 -0.01128992 -0.01341581 -0.03547974
    0.00670798  0.03213383 -0.02241655 -0.00337216 -0.00476903]
  [-0.02322083 -0.03858418 -0.01066352  0.04653597  0.01393992
   -0.00792106 -0.02555323  0.01062183  0.0105771   0.00702951]
  [ 0.02837155 -0.02027535 -0.00061259  0.04006502 -0.03408577
   -0.0471875   0.02612704 -0.00847112  0.0174451   0.03555336]
  [-0.02759372  0.00829092  0.02944385  0.00891739 -0.02488237
    0.03891957  0.02398211 -0.02025402  0.01355053 -0.01589119]
  [ 0.0386996  -0.02926265  0.02556217 -0.04915568 -0.00378739
    0.03255117  0.02815362  0.00071341  0.047612

In [14]:

embedded_docs[0]

#embedded for first sentence



array([   0,    0,    0,    0, 7117,  318,    9, 3154], dtype=int32)

In [15]:
print(model.predict(embedded_docs)[0])
#the first sentence vectors are from 0.0107.....-0.00476
#and so on
#https://www.youtube.com/redirect?q=https%3A%2F%2Fmachinelearningmastery.com%2Fuse-word-embedding-layers-deep-learning-keras%2F&event=video_description&v=TsXR7_vtusQ&redir_token=QUFFLUhqblE3Q1NKWDdLUVdsaHdsQ0pvd1hjOWlmbEtKd3xBQ3Jtc0tuY01vaThLbjB3cmxRTHJ5WF9OR09TbFVodGkxYkNDckplbTNxTkVaSldlQVNoU2NrTXpNQjA0OXpTX3ZNMWFzRWtVZHlOamFuNTkzNlkzbVNEdHZIeDhiVGcyRHhrMWgzVXBxSlZMcXloZVRiMExWUQ%3D%3D
#this link will explain more in depth


[[ 0.01076838  0.04307185 -0.01128992 -0.01341581 -0.03547974  0.00670798
   0.03213383 -0.02241655 -0.00337216 -0.00476903]
 [ 0.01076838  0.04307185 -0.01128992 -0.01341581 -0.03547974  0.00670798
   0.03213383 -0.02241655 -0.00337216 -0.00476903]
 [ 0.01076838  0.04307185 -0.01128992 -0.01341581 -0.03547974  0.00670798
   0.03213383 -0.02241655 -0.00337216 -0.00476903]
 [ 0.01076838  0.04307185 -0.01128992 -0.01341581 -0.03547974  0.00670798
   0.03213383 -0.02241655 -0.00337216 -0.00476903]
 [-0.02322083 -0.03858418 -0.01066352  0.04653597  0.01393992 -0.00792106
  -0.02555323  0.01062183  0.0105771   0.00702951]
 [ 0.02837155 -0.02027535 -0.00061259  0.04006502 -0.03408577 -0.0471875
   0.02612704 -0.00847112  0.0174451   0.03555336]
 [-0.02759372  0.00829092  0.02944385  0.00891739 -0.02488237  0.03891957
   0.02398211 -0.02025402  0.01355053 -0.01589119]
 [ 0.0386996  -0.02926265  0.02556217 -0.04915568 -0.00378739  0.03255117
   0.02815362  0.00071341  0.04761273  0.03912026]]
